# Generated by Django 5.2.15 on 2026-07-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_document_canonical_markdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="source_document_rollup",
        ),
    ]
