# Generated by Django 6.1 on 2026-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_project_source_document_rollup"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="has_validation_issues",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="validation_issues",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
