# Generated by Django 5.2.15 on 2026-07-01 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(
                blank=True,
                help_text="Researcher ORCID iD (e.g., 0000-0002-1825-0097)",
                max_length=19,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid ORCID (format: 0000-0000-0000-0000)",
                        regex="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                    )
                ],
            ),
        ),
    ]
