# Generated by Django 5.2.15 on 2026-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0003_schemauiconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateCheckRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[("schema", "Schema"), ("ontology", "Ontology")],
                        max_length=20,
                    ),
                ),
                ("module_name", models.CharField(max_length=100)),
                ("current_version", models.CharField(max_length=50)),
                ("available_version", models.CharField(blank=True, max_length=50)),
                ("is_update_available", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                ("release_notes", models.TextField(blank=True)),
                ("diff_summary", models.JSONField(default=dict)),
                ("download_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("module_type", "module_name")},
            },
        ),
    ]
