# Generated by Django 6.1 on 2026-08-21 17:52, hand-edited: reorder AddField before
# RemoveField and insert a data-preserving RunPython step in between so existing
# span->node/edge links survive the FK -> ManyToMany conversion instead of being
# silently dropped by RemoveField.

from django.db import migrations, models


def copy_fk_links_to_m2m(apps, schema_editor):
    TextSpan = apps.get_model("documents", "TextSpan")
    for span in TextSpan.objects.exclude(node__isnull=True).iterator():
        span.nodes.add(span.node_id)
    for span in TextSpan.objects.exclude(edge__isnull=True).iterator():
        span.edges.add(span.edge_id)


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_causalgraph_source_document"),
        ("documents", "0003_textspan_text_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="textspan",
            name="edges",
            field=models.ManyToManyField(
                blank=True, related_name="spans", to="annotation.edge"
            ),
        ),
        migrations.AddField(
            model_name="textspan",
            name="nodes",
            field=models.ManyToManyField(
                blank=True, related_name="spans", to="annotation.node"
            ),
        ),
        migrations.RunPython(copy_fk_links_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="textspan",
            name="edge",
        ),
        migrations.RemoveField(
            model_name="textspan",
            name="node",
        ),
    ]
