# Generated by Django 6.1 on 2026-08-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_span_node_edge_m2m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textspan",
            options={"ordering": ["start_char", "created_at"]},
        ),
    ]
