# Generated by Django 5.2.15 on 2026-07-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_causalgraph_source_document"),
        ("ontology", "0008_trigram_search"),
        ("projects", "0006_document_canonical_markdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OntologyTermSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_name", models.CharField(blank=True, max_length=200)),
                ("label", models.CharField(max_length=1000)),
                ("suggested_parent", models.CharField(blank=True, max_length=500)),
                ("definition", models.TextField(blank=True)),
                ("target_ontology", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted_upstream", "Submitted upstream"),
                            ("rejected", "Rejected"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upstream_issue_url", models.URLField(blank=True, max_length=500)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ontology_term_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ontology_term_suggestions",
                        to="annotation.causalgraph",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ontology_term_suggestions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
