# Generated by Django 5.2.15 on 2026-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0009_ontologytermsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologyrelease",
            name="scope_root_curies",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
