# Generated by Django 5.2.15 on 2026-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0010_ontologyrelease_scope_root_curies"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologyrelease",
            name="source_etag",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ontologyrelease",
            name="update_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ontologyrelease",
            name="upstream_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
