# Generated by Django 5.2.15 on 2026-07-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0006_document_canonical_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("model", models.CharField(default="claude-sonnet-5", max_length=100)),
                ("max_tokens", models.IntegerField(default=4096)),
                (
                    "api_key_env_var",
                    models.CharField(
                        blank=True,
                        help_text="Name of the environment variable holding the API key — never the key itself.",
                        max_length=100,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("on_assignment", "On Assignment"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("max_proposals_per_document", models.IntegerField(default=20)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_config",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
