# Generated by Django 5.2.15 on 2026-07-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_causalgraph_source_document"),
        ("llm", "0001_initial"),
        ("projects", "0006_document_canonical_markdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposerconfig",
            name="max_shots",
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name="FewShotExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_examples",
                        to="annotation.edge",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_examples",
                        to="projects.project",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_few_shot_examples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "selected_at"],
                "unique_together": {("project", "edge")},
            },
        ),
    ]
