# Generated by Django 5.2.15 on 2026-07-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_causalgraph_source_document"),
        ("llm", "0002_proposerconfig_max_shots_fewshotexample"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the edge's data as first proposed by the LLM, before any human edit — the baseline edit_distance is measured against.",
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("edit_distance", models.IntegerField(blank=True, null=True)),
                ("time_to_review_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "edge",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_outcome",
                        to="annotation.edge",
                    ),
                ),
            ],
        ),
    ]
