# Generated by Django 5.2.15 on 2026-07-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_proposaloutcome"),
        ("projects", "0006_document_canonical_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposaloutcome",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposal_outcomes",
                to="projects.document",
            ),
        ),
        migrations.AddField(
            model_name="proposaloutcome",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposal_outcomes",
                to="projects.project",
            ),
        ),
    ]
